# Generated by Django 4.2.7 on 2025-11-12 05:16

from django.db import migrations, models


def seed_subject_codes(apps, schema_editor):
    SubjectCode = apps.get_model("exams", "SubjectCode")
    subjects = [
        {
            "s_code": "BECS201",
            "subject": "Big Data Analytics",
            "course": "B.E.",
            "semester": "II",
            "branch": "CSE",
        },
        {
            "s_code": "BECS302",
            "subject": "Internet of Things",
            "course": "B.E.",
            "semester": "III",
            "branch": "CSE",
        },
        {
            "s_code": "BECS403",
            "subject": "Parallel Computing",
            "course": "B.E.",
            "semester": "IV",
            "branch": "CSE",
        },
        {
            "s_code": "BECS504",
            "subject": "Cryptography",
            "course": "B.E.",
            "semester": "V",
            "branch": "CSE",
        },
    ]

    for item in subjects:
        SubjectCode.objects.update_or_create(
            s_code=item["s_code"],
            defaults=item,
        )


def remove_seeded_subject_codes(apps, schema_editor):
    SubjectCode = apps.get_model("exams", "SubjectCode")
    SubjectCode.objects.filter(
        s_code__in=["BECS201", "BECS302", "BECS403", "BECS504"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0006_delete_scrutinyresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectcode",
            name="branch",
            field=models.CharField(
                choices=[
                    ("None", "None"),
                    ("CSE", "CSE"),
                    ("IT", "IT"),
                    ("ECE", "ECE"),
                    ("EEE", "EEE"),
                    ("MECH", "MECH"),
                    ("BioTech", "BioTech"),
                ],
                default="None",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="subjectcode",
            name="course",
            field=models.CharField(
                choices=[("None", "None"), ("B.E.", "B.E."), ("M.E.", "M.E.")],
                default="None",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="subjectcode",
            name="semester",
            field=models.CharField(
                choices=[
                    ("None", "None"),
                    ("I", "I"),
                    ("II", "II"),
                    ("III", "III"),
                    ("IV", "IV"),
                    ("V", "V"),
                    ("VI", "VI"),
                    ("VII", "VII"),
                    ("VIII", "VIII"),
                ],
                default="None",
                max_length=4,
            ),
        ),
        migrations.RunPython(seed_subject_codes, remove_seeded_subject_codes),
    ]
